config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('profile/', include('profiles.urls')),
    path('reserve/', include('meetingrooms.urls')),
]

urlpatterns += [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
]

profiles/urls.py
from django.urls import path, re_path

from .views import (
    signup,
    ProfileUpdateView,
    account_activation_sent_view,
    account_activate,
    set_meeting_rooms_count,
)

app_name = "profiles"

urlpatterns = [
    path("", signup, name="profile-signup"),
    path("<int:pk>/edit/", ProfileUpdateView.as_view(), name="profile-edit"),
]

urlpatterns += [
    path(
        "account-activation-sent/",
        account_activation_sent_view,
        name="account-activation-sent",
    ),
    path("activate/<uidb64>/<token>/", account_activate, name="activate"),
    path(
        "set-meeting-rooms-count/",
        set_meeting_rooms_count,
        name="set_meeting_rooms_count",
    ),
]

users/urls.py
from django.urls import path

from .views import home_view, signup_view, dashboard_view

app_name = "users"

urlpatterns = [
    path('', home_view, name='home'),
    path('signup/', signup_view, name='sign-up'),
    path('dashboard/', dashboard_view, name='dashboard'),
]

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        label="",
        max_length=30,
        min_length=5,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Username", "class": "form-control"}
        ),
    )

    email = forms.EmailField(
        label="",
        max_length=255,
        required=True,
        widget=forms.EmailInput(
            attrs={"placeholder": "Email", "class": "form-control"}
        ),
    )

    password1 = forms.CharField(
        label="",
        max_length=30,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Password", "class": "form-control"}
        ),
    )

    password2 = forms.CharField(
        label="",
        max_length=30,
        min_length=8,
        required=True,
        widget=forms.PasswordInput(
            attrs={"placeholder": "Confirm Password", "class": "form-control"}
        ),
    )

    location = forms.CharField(
        label="",
        max_length=30,
        required=False,
        widget=forms.HiddenInput(attrs={"display": "none"}),
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2", "location")


class MeetingRoomsCountForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["meeting_rooms_count"]

templates/app/dashboard.html
{% extends "base.html" %}

{% block title %}
	Dashboard
{% endblock %}

{% block content %}

	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-success mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}

	<h1 class="mt-5 text-center">Welcome {{ request.user }}</h1>
	<p class="text-left mt-5">Bio: {{ user.profile.bio }}</p>
	<p class="text-left">Joined: {{ user.profile.timestamp }}</p>

{% endblock content %}

templates/app/home.html
{% extends "base.html" %}

{% block title %}
	Home
{% endblock %}

{% block content %}

	{{ block.super }}

{% endblock content %}

templates/app/signup.html
{% extends "base.html" %}

{% block title %}
	Sign Up
{% endblock %}

{% block content %}
	
	{% if messages %}

	    {% for message in messages %}

		<!--Panel-->
		<div class="card border-danger mb-3">
		    <div class="card-header text-danger">
		        <p class="card-title">{{ message }}</p>
		    </div>
		</div>
		<!--/.Panel-->
	    
	    {% endfor %}

	{% endif %}

<div class="container mt-4">
<div class="row">
	<div class="col-md-4">
		
		<div class="list-group mt-5">
		    <a href="{% url 'users:home' %}" class="list-group-item list-group-item-action waves-effect">Home</a>
			{% if profile %}
		    <a href="{% url 'profiles:profile-signup' %}" class="list-group-item bg-secondary text-white waves-effect">
		    		Profile Sign up
		    	{% else %}
		    	<a href="{% url 'users:sign-up' %}" class="list-group-item bg-secondary text-white waves-effect">
		    		Sign up
		    {% endif %}		    	
		    </a>
		    <a href="{% url 'login' %}" class="list-group-item list-group-item-action waves-effect">Login</a>
		    <a href="{% url 'users:dashboard' %}" class="list-group-item list-group-item-action waves-effect">Dashboard</a>
		    <a href="{% url 'users:dashboard' %}" class="list-group-item list-group-item-action waves-effect">Profile</a>
		</div>

	</div>

		<div class="col-md-2"></div>

	<div class="col-md-4">
		<!-- Default form register -->
		<form class="border mt-5 border-secondary text-center p-3" method="post">
			{% csrf_token %}
		    <p class="h4 mb-4 text-secondary text-center">Sign up</p>

		    <!-- {{ form.as_p }} -->

			{% for field in form %}
		    <p>
	        	{{ field.label_tag }}
	        	{{ field }}
		        <!-- {% if field.help_text %}
		          <small style="color: grey">{{ field.help_text }}</small>
		        {% endif %} -->
		        {% for error in field.errors %}
		          <p style="color: red">{{ error }}</p>
		        {% endfor %}
		    </p>
		    {% endfor %}

		    <!-- Sign up button -->
		    <button class="btn btn-secondary my-4 btn-block" type="submit">Sign up</button>

		    <!-- Social register -->
		    <p>or sign up with:</p>

		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-facebook"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-twitter"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-linkedin"></i>
		    </a>
		    <a type="button" class="light-blue-text mx-2">
		        <i class="fa fa-github"></i>
		    </a>

		    <hr>

		    <!-- Terms of service -->
		    <p>By clicking
		        <em>Sign up</em> you agree to our
		        <a href="" target="_blank">terms of service</a>
		    </p>
		</form>
		<!-- Default form register -->
	</div>

	<div class="col-md-2"></div>

</div>
</div>

{% block script %}
<script type="text/javascript">
	function get_ip(json) {
		$("#id_location").val(json.ip);
	}
</script>

<script src="https://api.ipify.org?format=jsonp&callback=get_ip"></script>
{% endblock %}

{% endblock %}