config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('profile/', include('profiles.urls')),
    path('reserve/', include('meetingrooms.urls')),
]

urlpatterns += [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
]

profiles/urls.py
from django.urls import path, re_path

from .views import (
    signup,
    ProfileUpdateView,
    account_activation_sent_view,
    account_activate,
    set_meeting_rooms_count,
)

app_name = "profiles"

urlpatterns = [
    path("", signup, name="profile-signup"),
    path("<int:pk>/edit/", ProfileUpdateView.as_view(), name="profile-edit"),
]

urlpatterns += [
    path(
        "account-activation-sent/",
        account_activation_sent_view,
        name="account-activation-sent",
    ),
    path("activate/<uidb64>/<token>/", account_activate, name="activate"),
    path(
        "set-meeting-rooms-count/",
        set_meeting_rooms_count,
        name="set_meeting_rooms_count",
    ),
]

users/urls.py
from django.urls import path

from .views import home_view, signup_view, dashboard_view

app_name = "users"

urlpatterns = [
    path('', home_view, name='home'),
    path('signup/', signup_view, name='sign-up'),
    path('dashboard/', dashboard_view, name='dashboard'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Django App | {% block title %}{% endblock %}</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>

  <body>

    {% if not form %}
      {% include "navbar.html" %}
    {% endif %}

      <!-- Start your project here-->
      <div style="height: 100vh" class="container">

      	{% block content %}

          <div class="flex-center flex-column">
              <h1 class="animated fadeIn mb-4">This is a Meeting Room Management Web App</h1>

              <h5 class="animated fadeIn mb-3">Thank you for using our product. We're glad you're with us.</h5>

              <p class="animated fadeIn text-muted">Created by: Ali Zahedi</p>
          </div>

        {% endblock %}
      </div>
      <!-- /Start your project here-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    {% block script %}
    {% endblock %}
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
</body>

</html>

templates/navbar.html
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark secondary-color mb-5">
  <div class="container">
    <!-- Navbar brand -->
    <a class="navbar-brand" href="{% url 'users:home' %}">Django</a>

    <!-- Collapse button -->
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#basicExampleNav"
      aria-controls="basicExampleNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">
      <!-- Links -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'users:home' %}"
            >Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:dashboard' %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:sign-up' %}">Sign up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profiles:profile-signup' %}"
            >Profile SignUp</a
          >
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a
            class="nav-link"
            href="{% url 'profiles:profile-edit' user.profile.id %}"
            >Profile</a
          >
        </li>

        {% if user.is_authenticated and user.profile.role == 'manager' %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:set_meeting_rooms_count' %}">Set Meeting Rooms Count</a>
            </li>
        {% endif %}
        {% endif %}
      </ul>
      <!-- Links -->

      <!-- login and logout buttons -->
      <div class="my-1 mr-3">
        {% if user.is_authenticated %}
        <a
          class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3"
          href="{% url 'logout' %}"
          >Logout</a
        >
      </div>
      <div class="my-1 mr-3">
        <!-- user icon -->
        <div class="white-text">
          <i class="fa fa-user" aria-hidden="true"></i>
          {{ request.user }}
        </div>
        <div class="white-text">
          <i class="fa fa-user" aria-hidden="true"></i>

          {{ request.user.profile.role }}
        </div>
        {% else %}
        <a
          class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3"
          href="{% url 'login' %}"
          >Login</a
        >
        {% endif %}
      </div>
    </div>
    <!-- Collapsible content -->
  </div>
</nav>
<!--/.Navbar-->